### ISSUE TITLE
New tab group not recognized as active

### ISSUE THREAD

**Issue by JoelAnderson-UU** [gasparschott/obsidian-continuous-mode#12]
Great plugin!  

Here's my issue:

1. I have three tabs open, then I open a new tab group and open 3 tabs in that second tab group.
2. I select or start working on a note in the new tab group. (Doesn't that mean that the new tab group is then "active"?)
3. In the new tab group, I select "Toggle Continuous Mode" (with the command palette OR the tab-level chevron OR the three dots at the top right of the note.
4. Continuous mode is not toggled on – not in **either** tab group.
5. If I select a tab in the original tab group, I'm able to toggle continuous mode on for that tab group.
6. If I close that original tab group entirely (so that there is only one tab group), and I try to toggle continuous mode on, it doesn't work. 

So, there seems to be a problem with the way the plugin works with tab groups.

**Comment by gasparschott** [comment]
Thanks for the report—fixed.

**Comment by JoelAnderson-UU** [comment]
Thanks so much for your fast work on this.  It's now working fine!
