### ISSUE TITLE
[bug] problem with displaying of canvas type files

### ISSUE THREAD

**Issue by danieltomasz** [gasparschott/obsidian-continuous-mode#13]
Hi, great plugin, at first I didn't realize how much it will be useful for me!

There is currently problem with `.canvas` files - as they are per definition infinite, if they are open in a tab, scrolling through stacked tab group with them actually start scroll through canvas  internally (infinite white space) making it really hard to use. 

Ideas of solution:

1) Use fixed/locked view of canvas (don't scroll through canvas "internally within canvas", fix the view based on current elements, only double click or other user action will allow to change the default  view within canvas, in addition to view of canvas within stacked tabs) - it might be hard to implement
2) Exclude `.canvas` type file from stack (or allow user to exclude them by decision in settings) - might be a bit easier to implement

I am on Obsidian 1.5.11 on MacOS.

**Comment by gasparschott** [comment]
Thanks. Solution #2 is coming soon, along with other filtering options. I'll look into something along the lines of #1.
