### ISSUE TITLE
Find across all notes in continuous view

### ISSUE THREAD

**Issue by neocypher-x** [gasparschott/obsidian-continuous-mode#14]
If I try to open find, cmd + f, I can only find on a single note.

This plugin would be crazy powerful if you could find across all notes in the continuous view instead of one at a time.

**Comment by gasparschott** [comment]
Agreed; I'll have to look into how difficult it would be to implement. Thanks for the suggestion.

**Comment by gasparschott** [comment]
I'm unlikely to implement this option, as useful as it would be. I think a separate plugin would be preferable.
