### ISSUE TITLE
In new window not working

### ISSUE THREAD

**Issue by lifehaschanged** [gasparschott/obsidian-continuous-mode#15]
Thanks for the new update.
I have a problem. In a new window the toggle continous mode doesn't work.
But it's working in the main window.
Here is the error in the console:
<img width="301" alt="kjdfhgkfr" src="https://github.com/gasparschott/obsidian-continuous-mode/assets/81463128/272f2dec-79a2-4577-847b-2d5503f9e914">

**Comment by gasparschott** [comment]
Thanks, there will be a fix for this soon, hopefully in the next few days.

**Comment by gasparschott** [comment]
I've updated the plugin—Continuous Mode should now work with floating windows. Please let me know if you encounter any problems. Thanks.

**Comment by gasparschott** [comment]
Ah, interesting. I’ll look into that.

**Comment by gasparschott** [comment]
Greetings, this latest version fixes the disappearing notes problem when sorting floating windows. As for the styling problem you mentioned, I had noted it too, but it seems to be intermittent and unpredictable, so it is difficult to diagnose. Let me know if you detect a pattern, and I will also try to deal with it.

**Comment by gasparschott** [comment]
I believe I have a fix for the floating window problem. I'm not ready to post a new version of the plugin however (I'm adding features to open document and query block links in CM), so in the meantime, can you try adding this to your styles:
```
.workspace .mod-root .workspace-tabs.is_continuous_mode .workspace-tab-container .workspace-leaf .cm-editor .cm-content
{
	min-width:100%;
}
```
As for the arrow keys, I see there are yet more problems with floating windows. I'll try to fix this for the next release as well.
