### ISSUE TITLE
THANK YOU

### ISSUE THREAD

**Issue by Rhabarbara745** [gasparschott/obsidian-continuous-mode#16]
I've been missing this amazing feature since I first used Obsidian, thank you for making this possible!!! 

2 further ideas for improvement:
## Clicking on a folder opens this folder in Continuous Mode View (maybe let this turn on/off via a switch in the settings)
This would really increase the usability from my opinion as it would eliminate the need to right-click -> Continious Mode each time

## Not opening all notes at once
When opening big folder with a lot of notes, Obsidian seems to struggle a bit
Would it perhaps be possible to load the notes dynamically?

One of the best plugins for obsidian, makes reading notes so much more enjoyable 👏👏

**Comment by gasparschott** [comment]
Thanks for your thanks!
• Your first idea will be implemented in the next update, with options in the settings to choose how the folder items will be opened (e.g., in a new split left, appended in active tab group, replace, etc.)
• How many items are in the "big folders" you are opening? There is a warning already about opening a folder with more than 99 items; I've wondered if that limit should be lowered (or raised?). What do you mean about loading the notes "dynamically"? It it helps, It is already possible to open selected files in the File Explorer.

**Comment by gasparschott** [comment]
The latest update introduces the possibility to incrementally load files by setting a limit to the number of items to be loaded at one time. By repeatedly calling "Open or append ... in active tab group" you can open as few or as many items as you want. It's not the same as "infinite scroll", but I hope it works for you.

**Comment by Rhabarbara745** [comment]
Hi, sry for the late reply
Unfortunately I can't get it to work
When i open the settings, the new option “Allow single click to open.." is missing and an error is thrown

![image](https://github.com/gasparschott/obsidian-continuous-mode/assets/57756367/40570d41-587c-4038-9305-5186070afab9)

![image](https://github.com/gasparschott/obsidian-continuous-mode/assets/57756367/f28a1455-055f-421f-8c3a-5e240b7c968b)

**Comment by gasparschott** [comment]
Hmm, are you using the latest version? I just tried the setting and it worked for me without any errors.

**Comment by Rhabarbara745** [comment]
![image](https://github.com/gasparschott/obsidian-continuous-mode/assets/57756367/4b0a15dc-5069-4666-84db-bfb767c40a31)

Also tried it in two other vaults but same issue
if you need more information just let me know, happy to help

**Comment by gasparschott** [comment]
thanks, could you send me the data.json file from your plugins folder for continuous-mode?

**Comment by Rhabarbara745** [comment]
[data.json](https://github.com/user-attachments/files/15506678/data.json)

It looks the same in all of my vaults

**Comment by gasparschott** [comment]
Thanks again. Try the latest release (1.7.0), just uploaded; it should work now. There was a missing conditional check for the presence of one of the settings in the data.json file.

**Comment by Rhabarbara745** [comment]
Yesss it's working now and also the incremental loading is very cool, thanks a lot  🥳🥳

**Comment by gasparschott** [comment]
Very good to hear!

Sent with [Proton Mail](https://proton.me/) secure email.
