### ISSUE TITLE
Does this work with Longform?

### ISSUE THREAD

**Issue by dictionarymouse** [gasparschott/obsidian-continuous-mode#17]
Does this work with the [Longform](https://github.com/kevboh/longform/issues/131 ) plugin?

**Comment by gasparschott** [comment]
I haven't used Longform, but if you can have multiple notes open at a time, then it should work. Can you try and let me know?

**Comment by dictionarymouse** [comment]
Hmm... Longform creates an index file that it uses to order "scenes" independently of the file explorer order. 
The two plugins not incompatible per se, but not integrated, either.
It would be nice:

1. from **Continuous Mode** to be able to _Sort by **Longform**_ order, rather than manually having to reorder the tabs
2. from **Longform** to be able to _Open all scenes in a tab group in **Continuous Mode**_

**Comment by gasparschott** [comment]
I'm working on adding support for Longform (and File Tree Alternative). Basic functionality is already implemented, but since I don't use Longform myself, I have a few questions for you to help me with handling various possible situations:
When you are using Longform, do you tend to have all the project files open at once or just selected folders/files?
Do you have non-project files open in the same split?
Do you have more than one split open with files from the same project? 
Thanks.

**Comment by gasparschott** [comment]
Basic support for Longform has been added to the latest version (1.7.1). Let me know how it works for you. Thanks.

**Comment by dictionarymouse** [comment]
I should note that this is a relatively new vault, and I've not really. used Longform much/at all before. 
So far, tending to work with scenes in one split (occasionally a different file will get mixed in), and a group of related draft notes on the right. Sometimes other splits for characters, etc.
I had disabled Continuous Mode because embeds/transclusions disappear when it is enabled. 
I'm getting "No readable files found" when I try the right-click Continuous Mode Longform options.

**Comment by gasparschott** [comment]
Thanks for the report. Can you determine any pattern as to the different files getting mixed in? Are these files that are not in your Longform project? (I’m not exactly sure what you’re describing here, actually, but do I understand correctly that in general CM is working with the Longform pane to enable you to option scene/project files?)
As for the embeds and inclusions, have you enabled the “Exclude embedded files” option in the Continuous Mode settings?
If you get the “no readable files found”, check the file filtering options in the Continuous Mode settings to see if you have inadvertently not included any or all of the file types in your Longform project.
Let me know what you find out. Thanks.

**Comment by anandkumar89** [comment]
Longform stores list of files in it's index. Would it be possible to open a longform project in continuous mode direclty without seprately openning each file. A project could include almost 100 files - opening all of them at once may not be optimal choice. Instead keeping one scene above and below open could help? I do not underestand obsidian - as of now I've 7 files manually open and it seems to work smooth.

this would also free other tabs - if I want to open a separate file that should not be rendered in continous mode!

**Comment by gasparschott** [comment]
I haven't tested it for a while, but Longform compatibility should be available already. If you open the Longform panel and select a Project, you should be able to right- or control-click the project path to reveal the Continuous Mode menu, with which you can open all the project files at once. You can also show the menu for individual scenes by the same method. Let me know if this works for you or if I have misunderstood your request.

Note that you can limit how many files are opened at a time in the Continuous Mode settings.

Sent with [Proton Mail](https://proton.me/mail/home) secure email.
