### ISSUE TITLE
FR cssclasses background 

### ISSUE THREAD

**Issue by dictionarymouse** [gasparschott/obsidian-continuous-mode#18]
I use cssclasses to visually distinguish, for example, notes from drafts, using different fonts (size, family) and background colors. The font settings seems to be adopted but the background does not. 

(Edit for Clarity: It would be helpful to be able to either use the background color by cssclass and/or set the background color for a tab group.

P.S. thanks for this plugin

**Comment by gasparschott** [comment]
Try using .cm-editor as the target element. Because the plugin has to use display:contents for most of the higher-level tab leaf elements (which means their display box width and height are functionally 0), changing their background has no visible effect.

**Comment by dictionarymouse** [comment]
Thanks! .cm-editor worked perfectly.

**Comment by gasparschott** [comment]
If you need to color the background in reading view, use
.markdown-reading-view
or
.workspace-leaf-content[data-mode=“preview”] .view-content
