### ISSUE TITLE
Compatibility with Outliner.md Plugin

### ISSUE THREAD

**Issue by lifehaschanged** [gasparschott/obsidian-continuous-mode#19]
Hi,

Thanks for your recent updates!

In recent times, I've been impressed by a plugin that can be found here
https://github.com/Quorafind/Outliner.MD
Installable with BRAT:
https://github.com/TfTHacker/obsidian42-brat

Without going into other great features like edit embeds or edit backlinks, I'd like to describe the problem that arises when continuous mode and outliner.md are active at the same time. 

The problem occurs when you open an outliner.md file (button on the ribbon >  new outliner file)  and click then on the magnifying glass icon at the top right of the file. 

When both plugins are active, no text input field for the search is displayed. 

It doesn't matter whether continuous mode is active or not; the issue occurs in both cases. 
Only a single point is displayed when you click on the magnifying glass icon:

<img width="52" alt="2024-06-09 18_27_48-outliner-20240609182708 - Obsidian Sandbox - Obsidian v1 6 2" src="https://github.com/gasparschott/obsidian-continuous-mode/assets/81463128/ec42b61a-56da-4efe-8e3f-5860ef30a494">

It would be great if you could take a look at this sometime.

**Comment by gasparschott** [comment]
Thanks for the report. I’ve been curious about Outliner.MD as well, but have only just installed it because of your feedback.
I have found the cause of the problem—just a simple CSS rule—and will upload a fix soon; however before I do, I wonder if you have noticed any problems with the display of the outline itself; the Continuous Mode plugin does modify the CSS display mode of many editor items so it’s possible there some negative effects there as well. Can you let me know?

**Comment by gasparschott** [comment]
Could you possibly send me examples of the problematic outliner files? Thanks.

**Comment by gasparschott** [comment]
Hmm, I'm not sure I understand yet. I downloaded your outliner file, made a table.md file and added a simple 2 x 2 table and an embedded file ("Folder 2 Note 4"), and everything looks OK to me. Have I misunderstood what you did? 

Screenshot shows the outliner file and the table file open in Continuous Mode.

![test](https://github.com/gasparschott/obsidian-continuous-mode/assets/24398180/e5051d11-f32c-4fa3-bbb2-db656a519986)

**Comment by gasparschott** [comment]
Thanks for the step-by-step instructions. I now see what you mean. I’ll look into the problem—likely it is because of display:”contents” needed on note elements for CM to work.

**Comment by gasparschott** [comment]
The problems you were having should be solved now in the latest version 1.7.2. Arrow navigation mostly works, but I think that some of the problems stem from bugs within OutlinerMD itself; hopefully these will be worked out in future updates.
