### ISSUE TITLE
Notes in a new window don't seem to work in continuous mode

### ISSUE THREAD

**Issue by chris-lesage** [gasparschott/obsidian-continuous-mode#2]
I tried putting a group of notes into a new window `Open current tab in new window`, and then opening or dragging more notes into that new window.

The "Toggle continuous mode in active tab group" doesn't appear to work when run from this window.

A comment I made on Reddit explains what I'm trying to do:

> One thing I really wish for is for a way to open an arbitrary list of notes in a _single tab_. Because I have some tabs always open, like Kanban projects. So ultimately, there is nowhere for me to put this view without including those Kanbans in the view, or crowding the window with split groups. It would be amazing to store a few different continuous views, all side by side in tabs you can switch between.

**Comment by gasparschott** [comment]
Thanks for the report. This is a scenario I did not test for when developing the plugin. I’ll look into what can be done to fix it.

**Comment by gasparschott** [comment]
Fixed!
