### ISSUE TITLE
problem with  going   to  Kanban note from really long adjacent note when clicking on title

### ISSUE THREAD

**Issue by danieltomasz** [gasparschott/obsidian-continuous-mode#21]
I am in continous mode, I have 3 notes open in  this order from left to right
- 1 note - a kanban
- 2 note - a really long text note
- 3 note - another text note
I have a problem with switching  from 2 note to note 1 (containing kanban board created by kanban plugin) when I click on the titles in tabs, view scroll for a moment to note 1 and then is  going back to note 2
When the note 2 is short or I have open note 3, I dont have problem to go to kanban (note nr 1)

i am able to replicate this in sandbox vault.

**Comment by danieltomasz** [comment]
Ok - what I observed - the notes 1 and 2 are reversed in order in the scrolling mode (according to order from tabar note 1 should be first in order when scrolling, but they are switched

**Comment by gasparschott** [comment]
Thanks for the report. Can you try with the latest release (1.7.3), just uploaded?

**Comment by gasparschott** [comment]
Never mind, this update won't fix the problem. I'm working on it, though.

**Comment by gasparschott** [comment]
Has the problem been fixed for you with the latest release?

**Comment by danieltomasz** [comment]
Hi @gasparschott  Kanban note seems to be ok (I didnt tested it extensively), I notice other thing but I close this issue and open another one, thanks for fixing  the problem!
