### ISSUE TITLE
[Bug?] Clicking on wiki hyperlink in pinned note doesnt focus on newly opened  note 

### ISSUE THREAD

**Issue by danieltomasz** [gasparschott/obsidian-continuous-mode#23]
Again thanks for all the fixes and continuous work on the plugin!

I notice a behaviour that might be a bug;
The behaviour in Obsidian without continuous mode: Clicking on the wiki link in the pinned note move me to the linked note
Obsidian with continuous mode:  Clicking on the wiki link in the pinned note open the note in the background but don't focus the newly open note linked note, I need to manually click to focus on it

Although sometimes it focus on the note from the link (when the note is already  open)

Expected behviour:
Note will open and the focus move to note open in background (or this option might be set in settings as optional)

**Comment by gasparschott** [comment]
Hmm, interesting. I assume in the Obsidian Preferences you have enabled ```Editor > Always focus new tabs```? I've tested the behavior you describe and it seems to work fine for me, whether or not the tab group is in Continuous Mode. Could there also be a conflict with another installed plugin?
