### ISSUE TITLE
Option to pin all tabs

### ISSUE THREAD

**Issue by iSplasher** [gasparschott/obsidian-continuous-mode#26]
Hi, would an option to keep all tabs in the pane pinned be useful?

I find myself manually pinning all tabs to prevent a tab from being replaced by Obsidian when I open a new note.

- Cheers

**Comment by gasparschott** [comment]
Hmm, I'm not sure this sort of thing is within the scope of the plugin. I'd suggest a separate plugin (like https://github.com/patleeman/obsidian-open-in-new-tab; I haven't tried this). 

OTOH, in the  Continuous Mode settings, have you tried enabling "Allow single click to open FIle Explorer folders in Continuous Mode" and setting the default action to append? Currently, this only works for folders, but I will change it in the next release to work on files as well.
