### ISSUE TITLE
Tab group menu trigger only works on active tab group

### ISSUE THREAD

**Issue by Gorkycreator** [gasparschott/obsidian-continuous-mode#3]
The tab group menu can be triggered on non-active tab groups, so using it on any tab group will only affect the last one the user clicked on (whether that's the one that the user opened the menu for or not).

This [PR](https://github.com/gasparschott/obsidian-continuous-mode/pull/1) had a solution for this that moved the logic for getting the tab group id outside the toggle continuous mode function (line 209).

**Comment by gasparschott** [comment]
Thanks again. I've fixed this in the latest release.
