### ISSUE TITLE
[FR] Display current note and links within in continuous mode?

### ISSUE THREAD

**Issue by daxmonson** [gasparschott/obsidian-continuous-mode#5]
Really nice work you've done on this. 

Sometimes it would be useful (without embedding notes one by one) to just hit continuous mode and have it show the current note and all links within as one. Would be helpful with seeing how everything fits from a meta index note when building out structure. Not sure it's in your workflow, but thanks for considering it.

**Comment by gasparschott** [comment]
Apologies for not responding sooner. I'll have a think about this. Now that the "show all files in a folder" functionality has been implemented it may be that showing all links in a note will be possible without too much difficulty. Can't say how quickly I'll be able to get to it, though.

**Comment by gasparschott** [comment]
This functionality is coming soon.
