### ISSUE TITLE
[FR] Add a manual addition mode

### ISSUE THREAD

**Issue by wwjCMP** [gasparschott/obsidian-continuous-mode#6]
The current automatic addition is not very convenient to use, and I would like to add a manual addition mode

**Comment by gasparschott** [comment]
Sorry, I don't understand. Can you explain this and your other FR a little more clearly?

**Comment by wwjCMP** [comment]
What I mean is to manually add files that need to continue to be displayed under the current file, rather than automatically continuously displaying all files opened in the tab

**Comment by gasparschott** [comment]
If I understand correctly, you want to exclude certain files from continuous mode in the same tab split? It would seem to defeat the purpose of the plugin, IMO. I think you will need to open such files in a new split instead.

But what do you want to happen to the excluded files? Should they be hidden when viewing the other continuous mode files, but shown when you click on their tab header (hiding the other files)? I don’t know, maybe it could be done.
