### ISSUE TITLE
[FR] Reduce to paragraph

### ISSUE THREAD

**Issue by wwjCMP** [gasparschott/obsidian-continuous-mode#7]
I hope to provide a function similar to reducing the displayed content in canvas to specific paragraphs

**Comment by gasparschott** [comment]
Is this related to your previous comment? Can you explain further? Thanks.

**Comment by wwjCMP** [comment]
I think I misunderstood the main purpose of this plugin. I hope to integrate the content scattered in individual files on a continuous page. But it doesn't seem to be what this plugin is concerned about.

**Comment by gasparschott** [comment]
I suppose it depends on what it means to "integrate the content”. The plugin does show all the notes currently open in a tab split as a continuous page, but they remain separate files. In its current state the plugin is really rather simple: the main “continuous” functionality is accomplished with CSS, the files themselves are not touched. Hope that helps.

**Comment by gasparschott** [comment]
Perhaps you intend to merge files instead?

**Comment by wwjCMP** [comment]
In obsidian, I always tend to decentralize knowledge management.  Display them at the same time when needed, which is more in line with creative habits and more flexible.  Through free integration, knowledge points can be used in different places.

**Comment by wwjCMP** [comment]
In a word, it is the decentralized management and merged display of knowledge points.

**Comment by gasparschott** [comment]
I still don’t quite understand how the plugin fails in this area, but OK. Let me know if you have any other suggestions.
