### ISSUE TITLE
[BUG] I can't install the latest version 1.20

### ISSUE THREAD

**Issue by Drakemoor** [gasparschott/obsidian-continuous-mode#8]
I can't install the latest version 1.20

I've tried doing it in the sandbox vault to the same result. 

this is what I get in the console when I try to update. 
```
app.js:1 Obsidian Developer Console
app.js:1 Error: Request failed, status 404
    at new t (app.js:1:1978461)
    at UG (app.js:1:1978653)
    at app.js:1:1979330
    at app.js:1:237056
    at Object.next (app.js:1:237161)
    at a (app.js:1:235879)
(anonymous) @ app.js:1
```

**Comment by sbsamarski** [comment]
Same. There is a message that says "Failed to install plugin". Not sure if it has to do with the new version of Obsidian that just came out?

**Comment by gasparschott** [comment]
Fixed! There was a discrepancy between the tag numbrer and the manifest version number.
