### ISSUE TITLE
Sidebar icons and tabs buggy since last update

### ISSUE THREAD

**Issue by N3C2L** [gasparschott/obsidian-continuous-mode#9]
How to reproduce:

1. open a sandbox vault
2. install continuous mode
3. hover mouse cursor over the left sidebar icons on top > flashing icons
4. hover mouse cursor over tabs in the middle > flashing icons
5. same with right sidebar icons on top > flashing icons

I think some CSS might be wrong here.

**Comment by gasparschott** [comment]
Just uploaded a fix for this—I forgot to delete experimental CSS for a possible future update.

**Comment by N3C2L** [comment]
Hmm, I am not a developer, but I think you must update the manifest, so that we can download the new version inside Obsidian.

**Comment by gasparschott** [comment]
Have you tried recenlty? The latest update should be working. Let me know.

**Comment by N3C2L** [comment]
Inside Obsidian is only version 1.2.0 listed, not 1.21.

**Comment by gasparschott** [comment]
Ah, it may take a little time for the servers to update to the latest version.

**Comment by N3C2L** [comment]
Ok, thank you. Then I will try it tomorrow again.

**Comment by N3C2L** [comment]
I think your updated manifest.json must be listed here in the commits so that we can download it from obsidian:
<img width="845" alt="continious mode" src="https://github.com/gasparschott/obsidian-continuous-mode/assets/74585843/7156a9d1-9510-4348-950e-04ceb0b44fb4">

**Comment by gasparschott** [comment]
Thanks—done. This will teach me not to post a new release when I’m tired and distracted...

**Comment by N3C2L** [comment]
Awesome, thank you. The new version 1.21 is now listed inside Obsidian. Thanks for the new folder feature, can't wait to try it out! Have a good one!
